= AdminWebModule
:toc:

== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>across-standard-modules</groupId>
			<artifactId>spring-security</artifactId>
		</dependency>
	</dependencies>
----

=== Module dependencies

.Module dependencies
|===
|Module |Type |Description

|<<integration:acrossweb>>
|required
|Provides the web infrastructure for supporting `@AdminWebController`.

|<<integration:springsecurity>>
|required
|Provides the security infrastructure.

|<<integration:application-info>>
|optional
|Sets the _admin web title_ and _remember-me_ cookie name if not set explicitly.
|===

=== Module settings
tbd

== About the AdminWebModule

=== Remember me configuration
You can easily enable remember me support for the administration ui by setting the correct properties.  By default
the `TokenBasedRememberMeServices` are used, meaning the user password is encoded into the cookie value.  When using a
local memory database during development this can be unhandy when users get reinstalled upon application start.  If
the user password is also encoded using a random encoder (the default when using the `UserModule`) the remember me
cookies will not work after a restart.  The solution for this to configure either a `NoOpPasswordEncoder.getInstance()`
or a fixed password encoder in local development mode.

== Integration with other modules

[[integration:acrossweb]]
==== AcrossWebModule
Admin web creates its own `PrefixingRequestMappingHandlerMapping` that picks up all `@AdminWebController` and will
prefix all request mappings with the root path of the admin web module.

Provide an `AdminWebConfigurerAdapter` if you want to register interceptors that should only be applied to the
 admin web controllers.

[[integration:springsecurity]]
==== SpringSecurityModule
By default `AdminWebModule` adds a `SpringWebSecurityConfigurerAdapter` with default rules for all requests under
the admin web root.  If you wish to modify the default security rules, you must provide your own
`SpringWebSecurityConfigurerAdapter` that is positioned before the default `AdminWebSecurityConfiguration` instance.

If you create a new `SpringWebSecurityConfigurerAdapater` you will need to scope it correctly to the admin web root
path and provide all rules including things like login/logout and remember me.  If you are interested more in extending
the default configuration, you can extend `AdminWebSecurityConfiguration` and override the `customizeAdminWebSecurity`
adapter method.

.Example of disabling security headers on admin web
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
/**
 * Create a custom security configurer that extends from the
 * default AdminWebSecurityConfiguration but disables all
 * security headers.
 *
 * The @OrderInModule annotation will ensure that this
 * configurer will be positioned before the default configuration
 * once we add it to the AdminWebModule context.
 */
@Configuration
@OrderInModule(Ordered.HIGHEST_PRECEDENCE)
public class DisableAdminWebSecurityHeaders extends AdminWebSecurityConfiguration
{
	@Override
	protected void customizeAdminWebSecurity( HttpSecurity http ) throws Exception {
		http.headers().disable();
	}
}

...

// Add the custom security configuration to the AdminWebModule
AdminWebModule adminWebModule = new AdminWebModule();
adminWebModule.addApplicationContextConfigurer( DisableAdminWebSecurityHeaders.class );
----

[[integration:application-info]]
==== ApplicationInfoModule
If the `ApplicationInfoModule` is present in the context, the configured application information will be used
to set the default remember-me cookie name (based on the `ApplicationInfo.getApplicationId()`) and application title for
 the administration interface (based on the `ApplicationInfo.getApplicationName()` property).use DebugWebConfigurerAdapter to add interceptors only to debug web

Configuring admin access permissions
By default, access to the administration interface is restricted to users having the "access administration" permission. If you want to add one or more application specific permissions you have to override the property AdminWebModuleSettings.ADMIN_ACCESS_PERMISSIONS:
adminWebModule.setProperty( AdminWebModuleSettings.ADMIN_ACCESS_PERMISSIONS, new String[]{ "access administration", "custom permission 1", "custom permission 2" });

