= AdminWebModule
Arne Vandamme
1.1.1-SNAPSHOT
:toc: left
:sectanchors:
:module-version: 1.1.1-SNAPSHOT
:module-name: AdminWebModule
:module-artifact: admin-web-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/AdminWebModule
:spring-security-module-url: https://foreach.atlassian.net/wiki/display/AX/SpringSecurityModule

== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

.Module dependencies
|===
|Module |Type |Description

|<<integration:acrossweb>>
|required
|Provides the web infrastructure for supporting `@AdminWebController`.

|<<integration:springsecurity>>
|required
|Provides the security infrastructure.
|===

=== Module settings

All properties start with the *adminWebModule.* prefix.

|===
|Property |Type |Description |Default

|root-path
|`String`
|Root path for all admin web controllers.  All mappings will be relative to this path.
|/admin

|dashboard
|`String`
|Path within the admin web context for the initial dashboard.
|/

|title
|`String`
|Name of the application to be shown in the administration UI.
|

|access-permissions
|`String[]`
|Set of permissions that grant access to the administration interface.
|access administration

|locale.default-locale
|`Locale`
|Default locale that should explicitly be set when accessing the administration interface if no specific locale selected.
|`Locale.US`

|locale.options
|`List<Locale>`
|List of locales that can be selected on the login page.
|`Collections.emptyList()`

|login.template
|`String`
|View template for the login page.
|th/adminweb/login

|login.rememberMe.enabled
|`Boolean`
|Should remember me be enabled (will only be the case if a key is also configured).
|`true`

|login.rememberMe.key
|`String`
|Key used for creating the remember me cookie.
|

|login.rememberMe.cookie
|`String`
|Name of the remember-me cookie.
|rm-admin-web

|login.rememberMe.tokenValiditySeconds
|`Integer`
|Number of seconds a remember me token should be valid.
|_30 days_



|===

== What's new in this version?
:numbered!:
=== 1.1.1-SNAPSHOT

* all settings are now configurable through properties with Spring configuration metadata support
* login template now uses the `isRememberMeEnabled` attribute to determine if the remember-me checkbox should be shown
** this is a *breaking change* for custom templates

=== 1.1.0.RELEASE
Initial public release available on http://search.maven.org/[Maven central].

== About the AdminWebModule

== Integration with other modules

[[integration:acrossweb]]
==== AcrossWebModule
Admin web creates its own `PrefixingRequestMappingHandlerMapping` that picks up all `@AdminWebController` and will
prefix all request mappings with the root path of the admin web module.

Provide an `AdminWebConfigurerAdapter` if you want to register interceptors that should only be applied to the
 admin web controllers.

[[integration:springsecurity]]
==== SpringSecurityModule
By default `AdminWebModule` adds a `SpringWebSecurityConfigurerAdapter` with default rules for all requests under
the admin web root.  If you wish to modify the default security rules, you must provide your own
`SpringWebSecurityConfigurerAdapter` that is positioned before the default `AdminWebSecurityConfiguration` instance.

If you create a new `SpringWebSecurityConfigurerAdapater` you will need to scope it correctly to the admin web root
path and provide all rules including things like login/logout and remember me.  If you are interested more in extending
the default configuration, you can extend `AdminWebSecurityConfiguration` and override the `customizeAdminWebSecurity`
adapter method.

.Example of disabling security headers on admin web
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
/**
 * Create a custom security configurer that extends from the
 * default AdminWebSecurityConfiguration but disables all
 * security headers.
 *
 * The @OrderInModule annotation will ensure that this
 * configurer will be positioned before the default configuration
 * once we add it to the AdminWebModule context.
 */
@Configuration
@OrderInModule(Ordered.HIGHEST_PRECEDENCE)
public class DisableAdminWebSecurityHeaders extends AdminWebSecurityConfiguration
{
	@Override
	protected void customizeAdminWebSecurity( HttpSecurity http ) throws Exception {
		http.headers().disable();
	}
}

...

// Add the custom security configuration to the AdminWebModule
AdminWebModule adminWebModule = new AdminWebModule();
adminWebModule.addApplicationContextConfigurer( DisableAdminWebSecurityHeaders.class );
----
use DebugWebConfigurerAdapter to add interceptors only to debug web

Configuring admin access permissions
By default, access to the administration interface is restricted to users having the "access administration" permission. If you want to add one or more application specific permissions you have to override the property AdminWebModuleSettings.ADMIN_ACCESS_PERMISSIONS:
adminWebModule.setProperty( AdminWebModuleSettings.ADMIN_ACCESS_PERMISSIONS, new String[]{ "access administration", "custom permission 1", "custom permission 2" });

* login template has changed: isRememberMeEnabled
