<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.foreach.across</groupId>
		<artifactId>across-module-parent</artifactId>
		<version>5.0.1.RELEASE</version>
		<relativePath/>
	</parent>

	<artifactId>experimental-module-project</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>

	<name>experimental-module-project</name>
	<description>Experimental</description>

	<repositories>
		<repository>
			<id>foreach-nexus</id>
			<name>Foreach nexus</name>
			<url>https://repository.foreach.be/nexus/repository/public/</url>
		</repository>
	</repositories>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<timestamp>${maven.build.timestamp}</timestamp>
		<build.revision>development</build.revision>
		<maven.build.timestamp.format>yyyy-MM-dd HH:mm</maven.build.timestamp.format>
		<revision>0.0.3-SNAPSHOT</revision>
		<!-- Overridden from spring-boot-dependencies -->
		<maven-surefire-plugin.version>3.0.0-M5</maven-surefire-plugin.version>

		<admin-web-module.version>4.2.0-SNAPSHOT</admin-web-module.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.foreach.across.modules</groupId>
				<artifactId>admin-web-module</artifactId>
				<version>${admin-web-module.version}</version>
			</dependency>
			<dependency>
				<groupId>org.testcontainers</groupId>
				<artifactId>testcontainers-bom</artifactId>
				<version>1.15.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>

	</dependencyManagement>

	<modules>
		<module>experimental-module</module>
		<module>experimental-test-application</module>
		<module>experimental-module-distribution-assembly</module>
	</modules>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<failOnError>false</failOnError>
					<doclint>none</doclint>
					<sourcepath>
						target/delombok;target/generated-sources
					</sourcepath>
				</configuration>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
					<execution>
						<inherited>true</inherited>
						<id>aggregate</id>
						<goals>
							<goal>aggregate-no-fork</goal>
						</goals>
						<phase>prepare-package</phase>
						<configuration>
							<reportOutputDirectory>${project.reporting.outputDirectory}</reportOutputDirectory>
							<destDir>${project.version}/javadoc</destDir>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.asciidoctor</groupId>
				<artifactId>asciidoctor-maven-plugin</artifactId>
				<version>1.6.0</version>
				<inherited>false</inherited>
				<configuration>
					<sourceDirectory>docs</sourceDirectory>
					<sourceDocumentName>index.adoc</sourceDocumentName>
					<doctype>book</doctype>
					<outputDirectory>${project.build.directory}/site/${project.version}/reference</outputDirectory>
					<backend>html</backend>
					<attributes>
						<stylesheet>across.css</stylesheet>
					</attributes>
				</configuration>
				<executions>
					<execution>
						<id>output-html</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>process-asciidoc</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.junit.jupiter</groupId>
						<artifactId>junit-jupiter-engine</artifactId>
						<version>${junit-jupiter.version}</version>
					</dependency>
					<dependency>
						<groupId>org.junit.vintage</groupId>
						<artifactId>junit-vintage-engine</artifactId>
						<version>${junit-jupiter.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>3.0.0-M3</version>
				<configuration>
					<reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<skipAssembly>true</skipAssembly>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
