ExperimentalModuleTestApplicationModule.entities.food.views[exportToCsv].properties.currentAction=Status
EntityModule.entities.views[listView].controls.dateRange[selectDate]=Pikkiediedate
EntityModule.entities.views[listView].controls.dateRange[last14d]=Last 14 days (absolute)