== WebUtilityModule

=== General

Supports easier and more advanced configuration utilities for web-based actions.

[[web-utility-module-dependencies]]
=== Module dependencies

[options="header",cols="1,1,4"]
|===
|Module |Type |Description

|{entity-module-url}[EntityModule]
|optional
|Adds advanced/easier configuration for web utilities such as dependson which can be configured on either EntityPropertyDescriptors or ViewElements.
|===

=== Dynamic UI Actions

Daynamic actions can customize how views or components react to end-user actions, such as clicking a button.
These actions support defining a flow of technical actions that should be applied when the end user performs a given action.

==== Using actions

Actions and their handlers are configured using java code and executed by javascript.
An element can have multiple actions, which are conditionally executed based on the event that is send out within the DOM.
All actions that respond to the event are executed _asynchronously_.

Action handlers then follow up, once the action is executed.
The handlers are then executed in the order they are defined.
Handlers are usually smaller functions that execute a single step, such as moving elements around the dom, refreshing elements, reinitializing components...

Within the WebUtilityModule, some helpers are preconfigured.
For more advanced configurations, you will most likely need to extend the existing model.

.Example
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
EntityViewLinkBuilder linkBuilder;
ButtonViewElement element;

element.set( requestAction() <1>
                     .form( "[name=entityListForm]" )  <2>
                     .method( HttpMethod.POST )
                     .partial( "::body" )
                     .success( <3>
                             responseContentHandler() <4>
                                   .source( ".em-sortableTable-panel")
                                   .target( ".list-results" ),
                             initializeFormElements( ".em-sortableTable-panel" ) <5>
                     );
----
<1> Configure a request action on a `ButtonViewElement`.
The request action has no specific configuration on when to execute, so it will execute by default on a `click` event.
<2> The url for the request is configured to be executed on the currently active page rendered and it should fetch the partial `::body`.
The configured request should also submit the form identified by the jquery selector `[name=entityListForm]` and it is a POST request.
<3> When the request has a success response (with a response code in the 200 range) some handlers should be executed.
<4> A specific handler that retrieves the `.em-sortableTable-panel` from the response and replaces the content of `.list-results` with it.
<5> Reinitialize the `.em-sortableTable-panel`.

All in all, the above example would customize a button to submit a form and then replace and initialize a certain element on the page.

One step is remaining before the above would take any effect, and that is the registration of the required web resources.
WebUtilityModule defines a `WebResourcePackage` which holds the entire base configuration for actions and action handlers.
To register it, you can simply add the `WebUtilityModuleWebResources.NAME` package to the current `WebResourceRegistry`.

.Registering the required web resources
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
webResourceRegistry.apply(
        WebResourceRule.addPackage( WebUtilityModuleWebResources.NAME )
);
----

==== Available actions

As mentioned earlier, Actions are triggered by events on DOM elements.
In the backend, an action is defined by an `ActionAttribute`, which is a configuration object that is applicable to `ViewElements`.

Each action defines the following attributes:

[options="header",cols="2,4"]
|===

|Attribute |Description

| `action`
| Name of the action.
This is a unique identifier, which is then picked up on the client-side to integrate with the javascript.

| `event`
| The DOM event that defines when the action should execute.
Actions can be registered without events, but if missing they will not be executed.

|===

These attributes can be found on each of the mentioned actions below.
On specific implementations, defaults are provided, but they can be overridden by setting the attribute again.

===== Simple actions

Simple actions will do nothing special when triggered by an event on the corresponding element and will immediately execute their handlers.

[options="header",cols="1,4"]
|===

|Attribute |Description

| `action`
| Name of the action handler, defaults to `exm:simple`.

| `event`
| The DOM event that defines when the action should execute, defaults to `click`.

| handlers
| The action handlers that should be executed when the action is triggered.
Each of these handlers is triggered in order.

|===

===== Request actions

Request actions trigger a request on the client side when they are triggered by an event on the corresponding element.

[options="header",cols="1,4"]
|===

|Attribute |Description

| `action`
| Name of the action handler, defaults to `exm:simple`.

| `event`
| The DOM event that defines when the action should execute, defaults to `click`.

| url
| The url to which the request should be send to.
If let empty, the url of the current page on the client-side will be used.

| partial
| Defines whether a partial should be fetched instead of the entire page.
Optional.

| form
| The form that should be serialized for the request.
If the request is a `HttpMethod.POST` request, the form will be serialized to the request body, else it will be appended as request parameters.
Optional.

| method
| The HTTP request method that should be used.
Defaults to `HttpMethod.GET`.

| requestConfig
| A configuration map to extend the request configuration.
Can be used for example to configure specific headers that should be added to the request.

| copyOriginalRequestParameters
| Configures whether the request parameters that are currently present on the client-side page should be reused when this action is executed.
Defaults to `false`.

| success
| The action handlers that should be executed when the request has a `success` response (Status code in the 200-299 range).
Each of these handlers is triggered in order.

| redirect
| The action handlers that should be executed when the request has a `redirect` response (Status code in the 300-399 range).
Each of these handlers is triggered in order.

| failure
| The action handlers that should be executed when the request has a `failure` response (Status code outside the 200-399 range).
Each of these handlers is triggered in order.

| error
| The action handlers that should be executed when an error occurs in the handling of the request of one of its handlers.

|===

==== Available action handlers

Action handlers are used to define a series of steps that should be executed in order for an action.
They can do anything you want them to do.
In its core, they have a single attribute to link them to their client-side counterpart.

[options="header",cols="2,4"]
|===

|Attribute |Description

| `type`
| Type of the action handler.
This is a unique identifier, which is then picked up on the client-side to integrate with the javascript.

|===

===== Simple action handlers

The currently available simple action handlers support basic DOM manipulations.
First we'll take a look at the attributes it provides and then move on to some utilities that allow us to quickly set up some action handlers.

[options="header",cols="1,4"]
|===

|Attribute |Description

| `source`
| CSS3 selector that represents the source element.
A source element is optional as not every action handler requires input.

| `target`
| CSS3 selector that represents the target element.
The target element should always be specified.

|===

The above attributes don't tell us much in the sense of how to use them.
Let's jump to some of the utilities that are provided, which allow us to quickly set up some basic action handlers.
Most of these utilities specify the core `type` attribute to provide a link to the client-side functionality.

[options="header",cols="2,4"]
|===

|Utility |Description

| `simpleActionHandler`
| The most basic action handler.
This gives you a `SimpleActionHandlerAttribute` that needs to be fully configured to your use case.

| `responseContentHandler`
a| A response content handler can only be used within the context of a request action and handles the content in its response.
A `source` element is optional, if specified it will look for that element in the _content_ of the http response, if left empty, the source element will represent the entire response content.
The `target` selector defines which element's content should be replaced entirely with the source content.

NOTE: this handler does not support JSON response types.

| `moveHandler`
| An action handler that moves elements around the DOM.
It requires both a `source` and a `target` element to be specified.
The element defined by the `source` selector will be moved into the element represented by the `target` selector.

| `removeHandler( String target )`
| CSS3 selector that represents the target element.
The element defined by the `target` selector will be removed from the DOM.

| `clearHandler( String target )`
| CSS3 selector that represents the target element.
The element defined by the `target` selector will have it's content cleared.

| `closeModalHandler( String target )`
| CSS3 selector that represents the target element.
The element defined by the `target` selector should have a registered [Bootstrap modal] and will call its `hide` function.

| `initializeFormElements( String target )`
| CSS3 selector that represents the target element.
Reinitializes the element defined by the `target` selector.
This is practically the same as executing `EntityModule.initializeFormElements( target )`.

|===

===== Request action handler

Currently one request action handler is available, which can execute another request during the handling of the current action.
When the request of this handler is successfully executed, the element defined by the target attribute is replaced with the response text content.

A request action handler has the following attributes:

[options="header",cols="1,4"]
|===

|Attribute |Description

| url
| The url to which the request should be send to.
If let empty, the url of the current page on the client-side will be used.

| partial
| Defines whether a partial should be fetched instead of the entire page.
Optional.

| `form
| The form that should be serialized for the request.
If the request is a `HttpMethod.POST` request, the form will be serialized to the request body, else it will be appended as request parameters.
Optional.

| `method`
| The HTTP request method that should be used.
Defaults to `HttpMethod.GET`.

| `requestConfig`
| A configuration map to extend the request configuration.
Can be used for example to configure specific headers that should be added to the request.

| `target`
| Defines the target element that should be replaced with the content of the response.

|===

==== Registering custom actions

To register custom actions which can then be used on the client-side, additional javascript has to be configured.
Registering the client-side functionality for actions and their handlers can be done by registering additional web resources that come _after_ the `WebUtilityModuleWebResources`.
If so, a global `ExperimentalModule` object should be available that holds an `ActionFactory` and an `ActionHandlerFactory`.

These factories can be used to register _new_ actions or action handlers as well as execute them, all actions and action handlers return `Promise` objects to support error handling and execution order.

.Registering a new action
[source,javascript,indent=0]
[subs="verbatim,quotes,attributes"]
----
class MyAction {
  handle(action, context, actionHandlerFactory) {
    // perform some logic

    // execute handlers in order
    let sequence = Promise.resolve();
    action.handlers.forEach((handler) => {
      sequence = sequence.then(() => actionHandlerFactory.handle(handler, { action }));
    });
    return sequence;
  }
}

ExperimentalModule.actionFactory.register( "app:my-action", new MyAction()); <1>
----
<1> Registers the client-side execution for the action with name `app:my-action`.

An action is executed when the corresponding event is triggered.
To resolve the handling, the action that is executed is provided in combination with the context it is executed in and the `ActionHandlerFactory` that supports executing the handlers for an action.
In the above example, the action executes all its handlers in order and provides it with a context containing the action that is executed.
The context that is provided is a placeholder for custom implementations and uses, by default no information will be present.

Action resolving will automatically be configured once a `[data-action-load]` attribute is present.

.Registering a new action handler
[source,javascript,indent=0]
[subs="verbatim,quotes,attributes"]
----
class MyCustomHandler {
  handle(action, context) {
    if (action.source && action.target) {
        // perform some logic
      return Promise.resolve();
    }

    return Promise.reject(
      new ActionHandlerError(
        `Handler 'app:my-handler': both source and target are required`,
        action,
        context
      )
    );
  }
}

ExperimentalModule.actionHandlerFactory.register( "app:my-handler", new MyCustomHandler()); <1>
----
<1> Registers a custom action under the key `app:my-handler`.
This key corresponds to the type attribute of the action handler.

An action handler is similar to an action, being a `handle(action, context)` method.
The `action` holds the configuration of the action handler that should be executed, and the context holds information to execute the request.

What the context actually represents depends on the action that is executed.
For a simple action, the context by default only has one attribute, being the `action` that is executed.
For a request action, the context holds both an `action` and a `response` attribute.
The response in this case has been modified to also include the actual content of the response, represented by a `jsonContent` or `textContent` so that these can immediately be used.

=== Configuring conditional display

// dependson

=== Listview ajax pagination

You can change the default service side pagination of the sortable tables to ajax by using the `EntityViewAjax` configurer.

.Enable ajax pagination on a list view
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
  @Override
    public void configure(EntitiesConfigurationBuilder entities) {
        entities.withType(Company.class)
                .listView(EntityViewAjax.ajaxSettings.enableAjaxPagination()
                .ajaxUrlProvider(((linkBuilder, builderContext) -> linkBuilder.listView().withQueryParam("custom", "true").toUriString()))) <1>
)
----
<1> Register an optional url that will be used for pagination requests. By default the listView of the requested entity will be used.