= BootstrapUiModule
Arne Vandamme
2.0.1.RELEASE
:toc: left
:sectanchors:
:module-version: 2.0.1.RELEASE
:module-name: BootstrapUiModule
:module-artifact: bootstrap-ui-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/BootstrapUiModule
:javadoc-url: https://across.foreach.be/docs/across-standard-modules/BootstrapUiModule/{module-version}/javadoc
:autoNumeric-url: https://github.com/BobKnothe/autoNumeric
:datetime-url: https://github.com/Eonasdan/bootstrap-datetimepicker
:bootstrap-select-url: https://silviomoreto.github.io/bootstrap-select/

[copyright,verbatim]
--
Copyright (C) 2014-2017 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

[abstract]
== About
The {module-name} provides infrastructure for generating user interfaces based on Bootstrap.

Module website: {module-url}

:numbered:
== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

{module-name} only has a required dependency on AcrossWebModule.

== What's new in this version?
:numbered!:
=== 2.0.1.RELEASE
* DateTimeFormElements now have support for `LocalDate`, `LocalTime`, `LocalDateTime`
* `FormViewElement` and `FormViewElementBuilder` now allow you to configure either a command object or an `Errors` instance directly
** this makes it easier to resolve field errors for the `FormGroupElement` members of the form, without having to know the model attribute name
** when using the `errors` property directly, it is no longer required that the command object binding result is present on the model
* the default builders now usually support localized text patterns for any text property
** for example: `BootstrapUiBuilders.button().title("#{my.button=Default text}")`
* `TextboxFormElement` rendered inside a `FormGroupElement` which detects field errors, will now render the original input value if there are errors present
* direct use of `BootstrapUiFactory` or `BootstrapUiComponentFactory` is now discouraged, these interfaces have been deprecated
** use the stateless `BootstrapUiBuilders` facade instead
* added a `TooltipViewElement` with corresponding builder to quickly generate a tooltip with a default question mark icon
** see `BootstrapUiBuilders.tooltip()` for a builder method
* `FormGroupElement` has been refactored to support more descriptions
** a `tooltip` can be set which will be added to the label - after the label text and required indicator
** a `descriptionBlock` can be set which will be added to the group before the control
** a `helpBlock` can be set which will be added to the group after the control
** the property `renderHelpBlockBeforeControl` has been removed as the `descriptionBlock` is always rendered before the control, and the `helpBlock` always after the control

=== 1.2.0.RELEASE
* added `BootstrapUiBuilders` class that is a static facade for all builders
** `BootstrapUiFactory` and `BootstrapUiComponentFactory` beans are still available, but because both of them operate stateless, the facade was added to reduce wiring verbosity
* textbox improvements:
** `TextboxFormElement` has a property *disableLineBreaks* that will disable the ENTER key
** the `TextboxFormElementBuilder` will generate a valid single-line auto-sizing textarea if auto-size is requested on a normal textbox

=== 1.1.0.RELEASE
* added several <<NavComponentBuilder,builders for rendering menu structures>>: `DefaultNavComponentBuilder`, `BreadcrumbNavComponentBuilder` and `PanelsNavComponentBuilder`
** all nav related builders now also support message code snippets in `Menu` titles: putting for example _#{my.code=Item title}_ as value will be replaced by the Locale specific message for _my.code_ or by _Item title_ if the message code can't be resolved
* added support for <<bootstrap-select,bootstrap-select dropdown lists>> on `OptionsFormElementBuilder` and `SelectFormElement`
** allows for more advanced and user-friendly dropdown controls
* the BootstrapUiModule <<bootstrapui-javascript,javascript library supports adding initializer extensions>>

=== 1.0.0.RELEASE
Initial public release available on http://search.maven.org/[Maven central].

:numbered:
== ViewElement infrastructure
{module-name} provides a whole set of `ViewElement` infrastructure, meant for programmatically building user interfaces.

=== ViewElement
`ViewElement` implementations usually correspond to one or more HTML nodes.
{module-name} comes with a default set `ViewElement` implementation for rendering Bootstrap markup elements.
This is done through a collection of Thymeleaf processors for rendering `ViewElement` components.

You can render a `ViewElement` available on the model anywhere in a Thymeleaf template by using the _across:view_ tag.

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<across:view element="${myViewElement}" />
----

WARNING: You usually do not want to cache and reuse `ViewElement` components.
It is better to cache `ViewElementBuilder`.

=== Partial rendering
It is possible to render only a single `ViewElement` by passing the element name.
In that case all code will still be executed and all markup built, but only the markup of those elements will be written to the response.

The `ViewElement` name is specified in the *_partial_* parameter with a *::* prefix.

.Example
Assume we create a single `ViewElement` with a specific name.
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@GetMapping("/render")
String get() {
  model.addAttribute( "myViewElement", new TextViewElement( "myViewElement", "some text" ) );
}
----
And we render it in the following snippet:
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
<h1>title</h1>
<div th:fragment="mycontent">
	<across:view element="${myViewElement}" />
</div>
----

* _/render_ would output _<h1>title</h1><div>some text</div>_
* _/render?_partial=mycontent_ would output _<div>some text</div>_
* _/render?_partial=::myViewElement_ would output _some text_
* _/render?_partial=mycontent::myViewElement_ would also output _some text_

=== Default properties
In its most simple form, a `ViewElement` has the following properties:

[cols="1,3"]
|===

|*name*
|An optional internal name of the element.
This name can be used to retrieve the element from a `ContainerViewElement`.
Use `ContainerViewElementUtils` to query and modify containers.

See <<development-mode,development mode rendering>> for more information to retrieve generated view names.

|*elementType*
|A *required* type identification for the element.

|*customTemplate*
|An optional template name.
If a custom template is specified, it will be used to render the `ViewElement` instead of the default processor.
By default only Thymeleaf templates are supported.

|===

==== Custom template
Every `ViewElement` allows you to configure a *customTemplate*.
Only Thymeleaf fragments are supported, if you specify a Thymeleaf template without a fragment, a *render(component)* fragment will be appended.
The *component* variable will always contain the `ViewElement` instance that is being rendered.

You can use a different input variable by specifying the *${component}* manually in your template specification.

.Examples:

* `th/mymodule/mytemplate` results in `th/mymodule/mytemplate :: render(component)`
* `th/mymodule/mytemplate :: myfragment` results in `th/mymodule/mytemplate :: myfragment(component)`
* `th/mymodule/mytemplate :: myfragment(${someModelAttribute},${component})` results in `th/mymodule/mytemplate :: myfragment(attributeValue,component)`

NOTE: You should only use model attributes that are sure to be available when the template is being rendered.
It is usually best to pass the required values as attributes on the `ViewElement` itself.

You can use the `TemplateViewElement` if you only want to render a custom template and optionally pass it some attributes.

=== ViewElementBuilder
A `ViewElementBuilder` is a simple API for creating a `ViewElement` instance based on a configuration and a given `ViewElementBuilderContext`.

The `ViewElementBuilderContext` represents the runtime context when creating the element.
It is a way to pass attributes required for building the elements, and it also gives access to default request related beans like the `WebResourceRegistry` or the `WebAppLinkBuilder`.

{module-name} comes with a number of default `ViewElementBuilder` implementations for both simple elements and more complex components.

==== Global ViewElementBuilderContext
Most `ViewElementBuilder` implementations extend `GlobalContextSupportingViewElementBuilder`.
This class provides a parameterless `build()` method that will attempt to retrieve a `ViewElementBuilderContext` from the current thread, or from the request attached to the thread.
If no global `ViewElementBuilderContext` is registered however, calls to `build()` will throw an exception.

See the `ViewElementBuilderContextInterceptor` for an interceptor that creates a global `ViewElementBuilderContext`.

==== ViewElementBuilderContext in controllers
If there is a global `ViewElementBuilderContext` available, you can also `ViewElementBuilderContext` as a method argument in web controller methods.

==== Creating application links
The `ViewElementBuilderContext` provides a `buildLink(String)` method that will resolve a link using the `WebAppLinkBuilder` attribute that is available on the builder context.
By default the request-bound `WebAppLinkBuilder` is already set.

=== Development mode rendering

If development mode is active, all `ViewElement` names will be rendered in the markup.
Start and end of the element rendering will be marked by a HTML comment.
If the `ViewElement` is a node (xml-type element) it will also have a data attribute *data-ax-dev-view-element* containing the name.

.Example markup when rendered in development mode
[source,html,indent=0]
[subs="verbatim,quotes,attributes"]
----
<!--[ax:title]-->
<input name="entity.title" id="entity.title" data-ax-dev-view-element="title" type="text" class="form-control" value="" required="required" />
<!--[/ax:title]-->
----

NOTE: It is not required for a `ViewElement` to have a name, nor is it required for that name to be unique.

== Default elements
Most default elements can be created through the `BootstrapUiFactory` (instance) of `BootstrapUiBuilders` (static facade to the factories).

=== Overview
Although elements can be created directly, most have an equivalent `ViewElementBuilder`.
The builder implementation is rarely created directly but through the `BootstrapUiFactory`.

`BootstrapUiElements` contains the list of constants that define the specific element types.

[cols="1,2,4",options=header]
|===

|Element
|Builder
|Description

|`AlertViewElement`
|`AlertViewElementBuilder`
|Create a Bootstrap alert component.

|`AutoSuggestFormElement`
|`AutoSuggestFormElementBuilder`
|Configure and create a Typeahead based auto-suggest textbox.
See also the `AutoSuggestFormElementConfiguration` for configuration of the required datasets.

|`ButtonViewElement`
|`ButtonViewElementBuilder`
|Create buttons or button links.

|`CheckboxFormElement`
|`OptionFormElementBuilder`
|

|`ColumnViewElement`
|`ColumnViewElementBuilder`
|Creates a Bootstrap grid based layout.

|`DateTimeFormElement`
|`<<DateTimeFormElementBuilder>>`
|

|`FaIcon`
|
|Represents a Font Awesome icon.

|`FieldsetFormElement`
|`FieldsetFormElementBuilder`
|

|`FileUploadFormElement`
|`FileUploadFormElementBuilder`
|Creates a file input element.

|`FormGroupElement`
|`<<FormGroupElementBuilder>>`
|

|`FormViewElement`
|`FormViewElementBuilder`
|Create a form element with optional command attribute.

|`Glyphicon`
|
|Represents a Glyphicon icon.

|`HiddenFormElement`
|`HiddenFormElementBuilder`
|

|`InputGroupFormElement`
|`InputGroupFormElementBuilder`
|

|`LabelFormElement`
|`LabelFormElementBuilder`
|

|`LinkViewElement`
|`LinkViewElementBuilder`
|Regular hyperlink.

|`NumericFormElement`
|`<<NumericFormElementBuilder>>`
|

|`RadioFormElement`
|`<<OptionsFormElementBuilder,OptionFormElementBuilder>>`
|Creates a single radio button.

|`SelectFormElement`
|`<<OptionsFormElementBuilder>>`
|Creates a select control, either a regular HTML dropdown or a {bootstrap-select-url}[bootstrap-select].
Which type gets created depends on the presence of a `SelectFormElementConfiguration` object (`configuration` property).

|`SelectFormElement.Option`
|`<<OptionsFormElementBuilder,OptionFormElementBuilder>>`
|Creates a single select option.

|`StaticFormElement`
|
|Creates a readonly form-control.

|`TableViewElement`
|`<<TableViewElementBuilder>>`
|

|`TextareaFormElement`
|`<<TextboxFormElementBuilder>>`
|Multi-line text field.

|`TextboxFormElement` +
|`<<TextboxFormElementBuilder>>`
|Single-line text field - supporting HTML5 types.

|`TooltipViewElement` +
|`TooltipViewElementBuilder`
|Generate a simple tooltip element (text shown when hovering).
By default this is a link with a question mark icon.


|===

=== TableViewElementBuilder
Generate Bootstrap markup table structures.
Holds nested builders for head, foot and body sections.

=== TextboxFormElementBuilder
Will add textbox or textarea, based on multiline or not.
Also supports typing a textbox element.
In case of textarea will by default enable autosizing of the textarea and will register the javascript to do so.

=== OptionsFormElementBuilder
To quickly create a list of options, either as a select, list of checkboxes or list or radio buttons.

[[bootstrap-select]]
==== bootstrap-select support
If you want to create a more advanced {bootstrap-select-url}[bootstrap-select dropdown] instead of a simple HTML select, you can do so by specifying a `SelectFormElementConfiguration` object.
See the respective {javadoc-url}/com/foreach/across/modules/bootstrapui/elements/SelectFormElementConfiguration.html[javadoc for all configuration properties].

.Message codes
The `SelectFormElementConfiguration` allows you to configure the default text for the control.
These properties support message code text snippets which will be replaced if a `SelectFormElement` is built using the `OptionsFormElementBuilder`.

The following default message codes are used:

[options=header,cols="1,3,2"]
|===

| Property
| Message code
| Default text

| `selectAllText`
| BootstrapUiModule.SelectFormElementConfiguration.selectAllText
| Select all

| `noneSelectedText`
| BootstrapUiModule.SelectFormElementConfiguration.noneSelectedText
| Nothing selected

| `maxOptionsText`
| BootstrapUiModule.SelectFormElementConfiguration.maxOptionsText
| Limit reached ({0} items max)

| `countSelectedText`
| BootstrapUiModule.SelectFormElementConfiguration.countSelectedText
| {0} items selected

| `deselectAllText`
| BootstrapUiModule.SelectFormElementConfiguration.countSelectedText
| Deselect all

|===

NOTE: Message code replacement is performed when `SelectFormElementConfiguration.localize()` is called.
This is done automatically when using an `OptionsFormElementBuilder`

=== FormGroupElementBuilder
Takes a label and a control.
Can optionally take some help text.
Will render as a form group and will attempt to link the label to the control.

=== NumericFormElementBuilder
Uses the {autoNumeric-url}[JQuery autoNumeric plugin].
Supports decimal precision, localization and adding symbols (eg. for currency).

See `{javadoc-url}/com/foreach/across/modules/bootstrapui/elements/NumericFormElementConfiguration.html[NumericFormElementConfiguration]` for configuration options.

=== DateTimeFormElementBuilder
Represented as a date/time picker.
Uses the {datetime-url}[Eonasdan datetimepicker] JQuery plugin.

See `{javadoc-url}/com/foreach/across/modules/bootstrapui/elements/DateTimeFormElementConfiguration.html[DateTimeFormElementConfiguration]` for configuration options.

== Custom component builders
Accessible through the `BootstrapUiComponentFactory`.

[[NavComponentBuilder]]
=== Rendering menus
The `BootstrapUiComponentFactory` provides several builders for generating markup based on an Across `Menu`.
All builders extend `NavComponentBuilder` and support some of the same options.

[cols="1,1,4", options=header]
|===

|Builder class
|Factory method
|Description

|`DefaultNavComponentBuilder`
|`bootstrapUiComponentFactory.nav()`
|Converts a `Menu` component to a http://getbootstrap.com/components/#nav[Bootstrap nav].

|`PanelsNavComponentBuilder`
|`bootstrapUiComponentFactory.panels()`
|Converts a `Menu` component to a HTML5 `nav` where every group of `Menu` items is rendered as a panel with a heading.

|`BreadcrumbNavComponentBuilder`
|`bootstrapUiComponentFactory.breadcrumb()`
|Generates a http://getbootstrap.com/components/#breadcrumbs[breadcrumb] for the selected items of a `Menu`.

|===

==== Example
An example of generating a nav structure from a `Menu`.

.Custom menu definition and rendering
[source,java,indent=0]
[subs="verbatim,attributes"]
----
PathBasedMenuBuilder menu = new PathBasedMenuBuilder();
menu.item( "/one", "One", "#" ).order( 1 ).and()
    .group( "/two", "Two" ).order( 2 ).and()
    .item( "/two/one", "Sub item 1", "#" ).and()
    .item( "/two/two", "Sub item 2", "#" );

model.addAttribute(
    "customNav",
    bootstrapUiComponentFactory.nav( menu ).tabs().build( builderContext )
);
----

.Thymeleaf template
[source,xml,indent=0]
[subs="verbatim,attributes"]
----
<nav>
    <across:view element="${customNav}" />
</nav>
----

.HTML output generated
[source,xml,indent=0]
[subs="verbatim,attributes"]
----
<nav>
    <ul class="nav nav-tabs">
        <li><a href="#" title="One">One</a></li>
        <li class="dropdown">
            <a data-toggle="dropdown" href="#" title="Two" class="dropdown-toggle">
                Two <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a href="#" title="Sub item 1">Sub item 1</a></li>
                <li><a href="#" title="Sub item 2">Sub item 2</a></li>
            </ul>
        </li>
    </ul>
</nav>
----

==== Supported nav styles
You can generate specific nav structures using the `DefaultNavComponentBuilder` by specifying a nav style.

[cols="1,2,4",options=header]
|===

|Method
|CSS appended
|Remarks

|`simple()`
|
|Default mode.

|`navbar()`
|_navbar-nav_
|

|`tabs()`
|_nav-tabs_
|

|`pills()`
|_nav-pills_
|

|`stacked()`
|_nav-pills nav-stacked_
|

|===

All `NavComponentBuilder` implementations also support custom HTML attributes to be configured directly on the root element.

==== Default menu conversion behaviour
When mapping a `Menu` onto a nav, the following rules are followed:

* only 3 levels of items/groups are supported in the `Menu`
* an item is always rendered as a single item, even if it has children
* an item or group are only rendered if they are not disabled
* when an item is selected, the item itself as well as all its parent will have the _active_ css class
* a group is only rendered if it has at least one non-disabled child
* a group is rendered as a dropdown
* a group inside a group is rendered as a labeled section in the dropdown
* a group having only a single item is rendered as that single item unless the attribute _nav:keepAsGroup_ is set

==== Menu item title
All nav related builders support message code snippets in `Menu` titles.

Putting for example _#{my.code=Item title}_ as `title` property will be replaced by the `Locale` specific message for _my.code_ or by _Item title_ if that message code can't be resolved

==== Replacing group label by the selected item
By default the label of a dropdown will always be the title of the group.
If you want the label to be replaced by the label of the selected item, you should configure the `NavComponentBuilder` with `replaceGroupBySelectedItem`.

With `replaceGroupBySelectedItem` `true`, if no item is selected in the group, the dropdown label will still be the title of the group.
If an item is selected however, the dropdown label will be the item label, unless the group itself has the attribute _nav:keepGroupItem_ set to `true`.

==== Customizing nav rendering through the Menu
You can influence the generated output by setting reserved attributes on the `Menu` items.

NOTE: Attribute names mentioned here are available as constants on the `NavComponentBuilder` class.

The following attributes are support on `Menu` items:

[cols="1,4"]
|===

|_nav:icon_
|`ViewElement` or `ViewElementBuilder` to be prepended to the item text.

|_nav:iconOnly_
|Only applicable on a group.
If an icon is set, this will render the group itself as only the icon.

|_nav:linkViewElement_
|`ViewElement` or `ViewElementBuilder` to use when rendering the link inside the list item.
This will replace the standard link with the element generated.
Note that any value for *nav:icon* will be ignored.

Possible child items will still be rendered as a nested unordered list if the item is a group.
A custom link should handle opening the dropdown in that case.

|_nav:itemViewElement_
|`ViewElement` or `ViewElementBuilder` to use for rendering the entire list item of that `Menu`.
The `ViewElement` should take care of the full rendering, including any possible children.

|_nav:keepAsGroup_
|Only applicable on a group.
If set to `true` the group will always be rendered as a group, even though there is only a single item in it.

|_nav:keepGroupItem_
|Only applicable on a group and if `replaceGroupBySelectedItem` is set to `true`.
If so and _nav:keepGroupItem_ is set to true, the replace action will be suppressed and the group label will always be rendered.

*NOTE*: Attribute is only relevant for a `DefaultNavComponentBuilder`.

|_nav:panelStyle_
|Holds the CSS class that determines the panel styling.
If set, the default _panel-default_ class will be omitted.
Only applicable on group menu items that would result in a panel being rendered.

*NOTE*: Attribute is only relevant for a `PanelsNavComponentBuilder`.

|_nav:renderAsPanel_
|If set to _false_ on an group menu item that would be rendered as a panel (a group on the top level), no panel will be rendered but a sidebar nav list will directly be rendered.
Optionally a title will still be included if the group has one.  Non-panel lists do not support groups as items, these will be ignored.

*NOTE*: Attribute is only relevant for a `PanelsNavComponentBuilder`.

|_html:*_
|Any attribute with a name starting with _html:_ will be added as html attribute to the list item.
Name of the html attribute will be the menu attribute name without the _html:_ prefix.

|===

===== ViewElementBuilder attribute values
Some attributes support a `ViewElementBuilder`.
When rendering using a `ViewElementBuilder` the `ViewElementBuilderContext` will have an attribute *NavComponentBuilder.currentMenuItem* that contains the `Menu` the builder is rendering.


==== Examples
===== Adding an icon
Adding an icon to an item or group is easily done by setting the _nav:icon_ attribute with a `ViewElement` or `ViewElementBuilder` value.

.Example adding an icon as attribute
[source,java,indent=0]
[subs="verbatim,attributes"]
----
menu.item( "/dl", "Download", "#" )
    .attribute( NavComponentBuilder.ATTR_ICON, new GlyphIcon( GlyphIcon.DOWNLOAD ) )
    .order( 1 );
----

===== An icon based dropdown
If you set attribute _nav:iconOnly_ to `true`, the dropdown will only render the icon for the group.
If there is no icon value set on the group item, the dropdown will render the group title.

The children of the group (dropdown options) will always be rendered as full items.

If however the dropdown label is replaced by an item or the group only contains a single item, the item will also be rendered as only an icon.

.Example creating a dropdown represented by a single icon
[source,java,indent=0]
[subs="verbatim,attributes"]
----
menu.group( "/options", "Options", "#" )
    .attribute( NavComponentBuilder.ATTR_ICON, new GlyphIcon( GlyphIcon.COG ) )
    .attribute( NavComponentBuilder.ATTR_ICON_ONLY, true )
    .and()
    .item( "/options/dl", "Download", "#" )
    .attribute( NavComponentBuilder.ATTR_ICON, new GlyphIcon( GlyphIcon.DOWNLOAD ) );
----

== Creating custom view elements

=== Testing facilities
Across test contains some base classes for testing `ViewElement` infrastructure.

.AbstractViewElementBuilderTest
A base unit test for any `ViewElementBuilder` that extends `ViewElementBuilderSupport`.

.AbstractViewElementTemplateTest
Base integration test class for testing the rendering of a `ViewElement`.
Provides useful methods for rendering and inspecting the generated output.

=== BootstrapUiModule web resources
To provide the components client-side behaviour, BootstrapUiModule uses several web resource packages.
These often get registered automatically by the `ViewElementBuilder` used for generating a `ViewElement`.
Dependent packages will automatically be added as well.

==== Web resource packages
The following packages are available for adding to your template:

[cols="1,1,2",options="header"]
|===

| Package
| Package name
| Description

| `JQueryWebResources`
| jquery
| Registers JQuery library.

| `BootstrapUiWebResources`
| bootstrap
| Registers default Bootstrap CSS and javascript library. +
Depends on `JQueryWebResources`.

| `BootstrapUiFormElementsWebResources`
| bootstrapui-formelements
| Registers additional javascript and css for form element components like the datepicker, bootstrap-select etc. +
Depends on `BootstrapUiWebResources`.

|===

[[bootstrapui-javascript]]
==== BootstrapUiModule javascript object
When the javascript is registered correctly, a single `BootstrapUiModule` global object is available.
BootstrapUiModule javascript is fully JQuery based.

All BootstrapUiModule javascript can then be initialized by calling `BootstrapUiModule.initializeFormElements()`.
This method optionally takes an argument that is the node in which the form elements should be initialized.

This is automatically done on document load, but when using AJAX fragment rendering, you usually want to re-initialize the DOM element that was updated.

.Custom initializers
You can easily add a custom initializer function by adding it with `BootstrapUiModule.registerInitializer( callback )`.
There is no need to manually execute your callback on document load, as that will happen automatically by the BootstrapUiModule.

NOTE: Don't execute your callback on document load and then add it to the initializers.
Execution will happen automatically when calling `registerInitializer()`.

.Example registering a custom initializer
[source,html,indent=0]
[subs="verbatim,attributes"]
----
BootstrapUiModule.registerInitializer( function( node ) {
    $( '[data-my-attribute]', node ).each( function() {
        // initialize all elements with that attribute
    } );
} );
----

include::how-tos/index.adoc[]