acrossHibernate:
  generate-ddl: true

across:
  development:
    active: true

adminWebModule:
  title: Experimental module - TestApplication
  login:
    rememberMe:
      key: changeme


acrossModule:
  ExperimentalModule:
    resources: ../experimental-module/src/main/resources

spring:
  datasource:
    url: jdbc:h2:../local-data/db/experimental-module
    username: sa