[[appendix-entity-configuration-attributes]]
=== EntityConfiguration attributes
The following table lists commonly present attributes on an `EntityConfiguration`.

|===
|Key |Value

|`Repository.class`
|In case of an entity registered through a Spring Data repository.

|`RepositoryFactoryInformation.class`
|In case of an entity registered through a Spring Data repository.

|`PersistentEntity.class`
|In case of an entity registered through a Spring Data repository that exposed `PersistentEntity` information.

|`EntityQueryExecutor.class`
|Holds the `EntityQueryExecutor` that can be used for <<entity-query,custom `EntityQuery` execution>> and will be used by default for fetching entities.
Available if the `Repository` was supported by one of the <<entity-query-executor,default `EntityQueryExecutor` implementations>>.

|`EntityQueryParser.class`
|Holds the `EntityQueryParser` that should be used for <<entity-query-language,parsing EQL statements>> into a valid `EntityQuery`.
Available if the `EntityQueryExecutor.class` attribute is present.

|`EntityAttributes.TRANSACTION_MANAGER_NAME`
|Optionally holds the name of the `PlatformTransactionManager` that the repository for this entity uses.
EntityModule attempts to detect the transaction manager automatically for every Spring Data repository.
When set, this will enable transaction management for the default create, update and delete views.

|===

TODO: OptionGenerator, OptionIterableBuilder, EntityAttributes.OPTIONS_ENTITY_QUERY, EntityAttributes.OPTIONS_ALLOWED_VALUES

[[appendix-entity-property-descriptor-attributes]]
=== EntityPropertyDescriptor attributes
The following table lists commonly present attributes on an `EntityPropertyDescriptor`.

|===
|Key |Value

|`PersistentProperty.class`
|In case of a property of a `PersistentEntity` registered through a Spring Data repository.

|`Sort.Order.class`
|Contains the default `Sort.Order` if sorting is enabled on this property.
By default strings have an order that ignores case.

|`EntityAttributes.CONTROL_NAME`
|Optional: required to be a `String` value.
When present this value will be used as the form control name instead of the descriptor name.

|`EntityAttributes.NATIVE_PROPERTY_DESCRIPTOR`
|When present holds the Java beans property descriptor that was used to create the `EntityPropertyDescriptor`.
The presence of this attribute indicates that the property is not artificial but corresponds to an actual Java class property.

|===

TODO: OptionGenerator, OptionIterableBuilder, EntityAttributes.OPTIONS_ENTITY_QUERY, EntityAttributes.OPTIONS_ALLOWED_VALUES