= EntityModule
:toc:

== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>across-standard-modules</groupId>
			<artifactId>entity-module</artifactId>
		</dependency>
	</dependencies>
----

=== Module dependencies

.Module dependencies
|===
|Module |Type |Description

|<<integration:adminwebmodule>>
|optional
|Enables auto generated forms for managing the registered entities.
|===

=== Module settings

|===
|Property |Description |Default

|entityModule.entityValidator.registerForMvc
|Should the entity Validator instance be registered as the default validator for MVC databinding.
|true
|===

== About the EntityModule

=== EntityConfiguration and EntityAssociation

=== Integration with Spring Data repositories

== Configuring entity types

=== Using builders
Entities are usually automatically added to the `EntityRegistry` through the use of one or more `EntityRegistrar` beans.
The registrars will apply a default configuration, usually consisting of all properties, associations and views.

Customizing the `EntityRegistry` is done by implementing one or more `EntityConfigurer` beans in your modules.  These
receive an `EntitiesConfigurationBuilder` that effectively allows you to customize all registered `EntityConfiguration` instances.
Multiple `EntityConfigurer` beans can modify the same `EntityConfiguration`, the order in which they are applied will determine
the last value if they modify the same properties.

Investigate the javadoc of the `EntitiesConfigurationBuilder` and child builders to discover all possible configuration options.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@AcrossDepends(required = "EntityModule")
@Configuration
public class UserEntitiesConfiguration implements EntityConfigurer
{
	@Override
	public void configure( EntitiesConfigurationBuilder configuration ) {
		// By default permissions cannot be managed through the user interface
		configuration.entity( Permission.class ).hide();
	}
}
----

=== Configuring properties
Properties for an entity can be configured through the builders as well.  New properties can be added or the default
properties can modified.  How properties are configured determines how they will be rendered on the generated forms.

hidden:: A hidden property will by default not be returned when requesting all properties from an `EntityPropertyRegistry`.
You can still get this property directly however, the `hidden` state means a property will not advertise itself, you must
know of its existence.

readable:: Any readable property can be rendered in all views.  This state means that a form control can always be generated,
 even though it might very well be readonly if the property is not `writable`.

writable::  A writable property can be rendered in form views.  In case a property is writable but not readable, the
 property can only be included in forms but not in other views.

WARNING: The `hidden` state has no correlation with a hidden form control.  Setting a property to be rendered as a hidden
form control can only be done through configuring the right `ViewElement` information for that property.

==== Configuring a label
An entity with a corresponding `EntityConfiguration` always has a label, this is a textual representation of the entity
 in for example lists.  This could be the *name* or the * title* property for example.  By default the label corresponds
 to a custom generated property *#label* that defaults to calling `toString()` on the entity.

You can configure the label using the `label()` method on a `PropertyDescriptorBuilder`.  This is equivalent to calling
   `property("#label")`.  If you want to use another property as the base for label generation, you can configure this
   on the `EntityConfigurationBuilder` by calling `label("propertyName")`.  This will copy all settings from the source
   property to the *#label* property, but keep in mind it still is a separate property that can be customized.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Override
public void configure( EntitiesConfigurationBuilder configuration ) {
    // Configure the username to be used as label for a User entity
    configuration.entity( User.class ).label( "username" );

    // Configure the group name to be used as base label, but modify the value fetcher so
    // the label is prefixed with Group
    configuration.entity( Group.class )
                    .properties().label( "name" ).spelValueFetcher( "'Group: ' + name" );
}
----

If you do not wish to use the *#label* property at all as default entity label, you can customize the `Printer` used for label
 generation by modifying the `EntityModel`.

NOTE: As *#label* is a generated property, sorting is not enabled by default.  If you configure the label using an existing
property, the sortable attribute will be copied as well and sorting on label will be possible.

=== Creating an EntityConfiguration manually

==== Attributes to configure

Some attributes are mandatory, others are optional but will often impact how much functionality is available
 out of the box.  You can configure any attribute you like, see the section on [automatic-attributes] for a list
 of common attributes provided by other registrars.

==== EntityQueryExecutor

In order for generated views to work automatically, an `EntityConfiguration` should have an `EntityQueryExecutor`
  attribute.  The `EntityQueryExecutor` is a generic interface that supports the simple `EntityQuery` abstraction
  for fetching entities from the backing repository. Default implementations exist for `JpaSpecificationExecutor`
  and `QueryDslPredicateExecutor`.

=== Automatic registration of entity types

[[automatic-attributes]]
==== Registered EntityConfiguration attributes

|===
|Key |Value

|`Repository.class`
|In case of an entity registered through a Spring data repository.

|`RepositoryFactoryInformation.class`
|In case of an entity registered through a Spring data repository.

|`PersistentEntity.class`
|In case of an entity registered through a Spring data repository that exposed `PersistentEntity` information.

|`EntityQueryExecutor.class`
|Holds the `EntityQueryExecutor` that will be used for entity fetching.
|===

==== Registered EntityPropertyDescriptor attributes

|===
|Key |Value

|`PersistentProperty.class`
|In case of a property of a `PersistentEntity` registered through a Spring data repository.

|`EntityAttributes.SORTABLE_PROPERTY`
|Contains the name of the property that can be sorted on when sorting is enabled on this property.  In case
of a `PersistentProperty`, this will be the name of that `PersistentProperty`.

|===


== Integration with other modules

[[integration:adminwebmodule]]
==== AdminWebModule

If the `AdminWebModule` is present entity management controllers will be created for all registered entity configurations.
If you want to avoid the automatic registration of entity management controllers for a particular entity type, you should
set the `EntityConfiguration` as `hidden`.  This will effectively disable the default entity controllers for that type,
and hide the existence of the entity type from the administration interface.

You can also hide one or more associations.  By default an association will not be shown if one of the participating
entities is hidden.  If you specify the `hidden` property of an `EntityAssociation` explicitly, that value will take
precendence of the entity configurations.  This way it is possible to generate management pages for associated
entities, but not for the main entity type.

== Entity associations

The `EntityModule` attempts to automatically detect related entities and creates associations mainly to facilitate UI
generation.  Currently `@OneToMany`, `@ManyToMany` and `@ManyToOne` annotations from `javax.persistence` API are all
scanned and used to build `EntityAssociation` entries.

In the administrative UI the management of related entities can often be done either through the property or the association.
This is especially the case for `@ManyToMany` and `@OneToMany` associations that are mapped through a property with collection type.
By default related entity management will be done through the property and the association will be generated but hidden.

NOTE: If you want to enable management through the association interface, you should manipulate the `hidden` property of
both the association and the property using an `EntityConfigurer`.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Override
public void configure( EntitiesConfigurationBuilder configuration ) {
    // Groups should be managed through the association instead of the property
    configuration.entity( MachinePrincipal.class )
                 .properties().property( "groups" ).hidden( true ).and().and()
                 .association( "machinePrincipal.groups" ).show();
}
----

== Entity views

=== List views

==== List summary view

It is possible to activate a detail view inline in a list view.  If the `EntityConfiguration` or `EntityAssociation` has
as view named *listSummaryView* a summary pane will automatically become available when clicking on the item row in the table.
The summary pane is called using AJAX and only the _content_ fragment of the page will be rendered.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
// Activate a summary view in the main user results table using a custom Thymeleaf template
configuration.entity( User.class ).view( EntityListView.SUMMARY_VIEW_NAME ).template( "th/myModule/userSummary" );
----

=== Custom views

=== EntityLinkBuilder

An `EntityConfiguration` or `EntityAssociation` can have one or more `EntityLinkBuilder` instances registered in its atttributes.
An `EntityLinkBuilder` is used to create application links to management controllers for the entity.  By default the `EntityModule`
will create an `EntityLinkBuilder` for the management pages in admin web if `AdminWebModule` is present, and this link builder
will be registered as the attribute with `EntityLinkBuilder` class as key.

You can use the `EntityLinkBuilder` directly for example in redirects, often the specific `EntityLinkBuilder` is overridable per view.
All links the `EntityLinkBuilder` generates are entirely configurable, please refer to the javadoc for all possible settings.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
EntityLinkBuilder linkBuilder = entityConfiguration.getAttribute( EntityLinkBuilder.class );

// Will create a link of the form "/entities/{parent}/{parentId}/update"
String path = linkBuilder.update( parent );
----

==== EntityLinkBuilder for associations
Associations usually also have an `EntityLinkBuilder` registered, it is possible to create links to items that are an association
from a parent entity.  To achieve this you must _scope_ the `EntityLinkBuilder` to the parent entity it belongs to.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
EntityLinkBuilder linkBuilder = entityConfiguration.getAttribute( EntityLinkBuilder.class );

EntityConfiguration associated = association.getTargetEntityConfiguration();
EntityLinkBuilder associatedLinkBuilder = association.getAttribute( EntityLinkBuilder.class )
                                                     .asAssociationFor( linkBuilder, parent );

// Will create a link of the form "/entities/{parent}/{parentId}/associations/{associationName}/{childId}/update"
String path = associatedLinkBuilder.update( child );
----


== Customizing generated Entity views
The following section gives an overview of common custimizations for generated entity views.

=== Changing entity names, property names or other labels
Labels are resolved using a message code hierarchy.  Simply define one or more message sources specifying the properties
  you want.  Unless custom `EntityMessageCodeResolver` instances are being used, message codes are generated as follows:

|===
|Message code|Description

| enums.*EnumName*.*EnumValue*
| Message code for a single enum value label. +
Example: _enums.Numbers.ONE_

| *EntityPrefix*.name.singular
| Label for an entity in singular form, for use outside or at the beginning of a sentence. +
Example: _UserModule.entities.user.name.singular_

| *EntityPrefix*.name.plural
| Label for an entity in plural form, for use outside or at the beginning of a sentence. +
Example: _UserModule.entities.user.name.plural_

| *EntityPrefix*.name.singular.inline
| Label for an entity in singular form, for use within a sentence. If not explicitly specified, the label is
generated based by lower-casing the non-inline version. +
Example: _UserModule.entities.user.name.singular.inline_

| *EntityPrefix*.name.plural.inline
| Label for an entity in plural form, for use within a sentence.  If not explicitly specified, the label is
 generated based by lower-casing the non-inline version. +
Example: _UserModule.entities.user.name.plural.inline_

| *EntityPrefix*.properties.*propertyName*
| Label for a single entity property. +
Example: _UserModule.entities.user.properties.username_

| *EntityPrefix*.properties.*propertyName*[description]
| Description text for a property.  If not empty this will be rendered in a help block on forms. +
Example: _UserModule.entities.user.properties.username[description]_

| *EntityPrefix*.properties.*propertyName*[placeholder]
| Placeholder text for a property.  Will be used for certain controle like textbox. +
Example: _UserModule.entities.user.properties.username[placeholder]_

| *EntityPrefix*.validation.*validatorKey*
| Description text for a validation error message.  Optionally can be suffixed with the specific property name. +
Example: _UserModule.entities.user.validation.NotBlank_,  _UserModule.entities.user.validation.alreadyExists.username_


| actions.*
|

| pageTitle.*


|===

* _Entity_ codes are camel cased
* EntityPrefix: ModuleName.entities.entityName, or EntityModule.entities.entityName or simply entityName
* Hierarchical lookups: entity can be removed, module can be replaced by EntityModule

=== Selecting properties
`EntityPropertySelector`, incremental builders, keep current, select all, select all without default filter, exclude

=== Customizing fieldsets

=== Customizing entity validation

By default annotation validation is performed on all entities.  Customizing validation can be done by simply
specifying a `Validator` bean that supports the specific entity type.  You can use the `EntityValidatorSupport` as
  as base class to extend the default annotation based entity validation.

If more than one `Validator` could be applied,
you will manually have to set the `Validator.class` attribute on the `EntityConfiguration` to the correct one.

=== Customizing textbox elements

`TextboxFormElement.Type` can be set as an attribute on the `EntityPropertyDescriptor`.  If set and the property is
generated as a `TextboxFormElement`, that type will be used.

You can add default post processors to the `TextboxFormElementBuilderFactory` to customize the autodetection.

== To be done:
* view processor







