== EntityModule
:toc:

=== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>across-standard-modules</groupId>
			<artifactId>entity-module</artifactId>
			<version>{across-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

.Module dependencies
|===
|Module |Type |Description

|<<integration:adminwebmodule>>
|optional
|Enables auto generated forms for managing the registered entities.
|===

=== Module settings

|===
|Property |Description |Default

|entityModule.entityValidator.registerForMvc
|Should the entity Validator instance be registered as the default validator for MVC databinding.
|true
|===

== About the EntityModule

=== Integration with Spring Data repositories

=== Creating an EntityConfiguration manually

=== Integration with other modules

[[integration:adminwebmodule]]
==== AdminWebModule

== Entity views

=== EntityLinkBuilder

An `EntityConfiguration` or `EntityAssociation` can have one or more `EntityLinkBuilder` instances registered in its atttributes.
An `EntityLinkBuilder` is used to create application links to management controllers for the entity.  By default the `EntityModule`
will create an `EntityLinkBuilder` for the management pages in admin web if `AdminWebModule` is present, and this link builder
will be registered as the attribute with `EntityLinkBuilder` class as key.

You can use the `EntityLinkBuilder` directly for example in redirects, often the specific `EntityLinkBuilder` is overridable per view.
All links the `EntityLinkBuilder` generates are entirely configurable, please refer to the javadoc for all possible settings.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
EntityLinkBuilder linkBuilder = entityConfiguration.getAttribute( EntityLinkBuilder.class );

// Will create a link of the form "/entities/{parent}/{parentId}/update"
String path = linkBuilder.update( parent );
----

==== EntityLinkBuilder for associations
Associations usually also have an `EntityLinkBuilder` registered, it is possible to create links to items that are an association
from a parent entity.  To achieve this you must _scope_ the `EntityLinkBuilder` to the parent entity it belongs to.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
EntityLinkBuilder linkBuilder = entityConfiguration.getAttribute( EntityLinkBuilder.class );

EntityConfiguration associated = association.getTargetEntityConfiguration();
EntityLinkBuilder associatedLinkBuilder = association.getAttribute( EntityLinkBuilder.class )
                                                     .asAssociationFor( linkBuilder, parent );

// Will create a link of the form "/entities/{parent}/{parentId}/associations/{associationName}/{childId}/update"
String path = associatedLinkBuilder.update( child );
----


[[form-elements]]
== Form elements

Implementation is always disconnected from the selected value (entity).  Single form element could be used
to render multiple entities.

=== Form element types
Every `FormElement` has a unique element type `getElementType()`, this type is a simple String property that can be
 used how the element should render and behave.

.Common form element types
|===
|Element type |Description

|textbox
|

|hidden
|

|select
|

|multi-checkbox
|

|checkbox
|Renders a single checkbox.

|===

==== Type lookup strategy

.Default lookup strategy for common form element types
|===
|Property type |Form element type

| `String`, `Number`, `Date`
| textbox

| `Boolean`
| checkbox

| `Enum`
| select

| `Collection<?>`, `Array`
| multi-checkbox

|===

==== Specifying the default type for a property

=== Form element factories
hierarchy: assembler, builderfactory, builder, element (scopes)

messagecoderesolver

=== Common FormElement implementations
==== Basic functionality
label, value, required, print, customTemplate

==== HiddenFormElement
Renders a hidden HTML input type.

==== CheckboxFormElement
Renders a single checkbox, the `isChecked(Object)` method can be used to determine if the checkbox should be checked
for the given entity.

==== TextboxFormElement
Renders either a text input type or a textarea depending on the `multiLine` property.
Supports `maxLength` property to specify the maximum length of text the box should support.

==== SelectFormElement
This implementation is used for several element types and can be used to render any collection of selected values.
The `options` property determines the list of possible values in the form of `SelectOption` instances.  The associated
`SelectFormElementBuilder` takes a `SelectOptionGenerator` implementation that is used to generate the list of possible
options when building the element.

`SelectFormElement` provides a setter method for `elementType` because the base implementation can easily be used
for different types of controls.  The default template renders both `select` and `multi-checkbox` element types
from `SelectFormElement` instances.

configuration:
defining a custom view
registering custom properties






