= EntityModule
:toc:

== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>across-standard-modules</groupId>
			<artifactId>entity-module</artifactId>
			<version>{across-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

.Module dependencies
|===
|Module |Type |Description

|<<integration:adminwebmodule>>
|optional
|Enables auto generated forms for managing the registered entities.
|===

=== Module settings

|===
|Property |Description |Default

|entityModule.entityValidator.registerForMvc
|Should the entity Validator instance be registered as the default validator for MVC databinding.
|true
|===

== About the EntityModule

=== EntityConfiguration and EntityAssociation

=== Integration with Spring Data repositories

== Configuring entity types

=== Using builders
Entities are usually automatically added to the `EntityRegistry` through the use of one or more `EntityRegistrar` beans.
The registrars will apply a default configuration, usually consisting of all properties, associations and views.

Customizing the `EntityRegistry` is done by implementing one or more `EntityConfigurer` beans in your modules.  These
receive an `EntitiesConfigurationBuilder` that effectively allows you to customize all registered `EntityConfiguration` instances.
Multiple `EntityConfigurer` beans can modify the same `EntityConfiguration`, the order in which they are applied will determine
the last value if they modify the same properties.

Investigate the javadoc of the `EntitiesConfigurationBuilder` and child builders to discover all possible configuration options.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@AcrossDepends(required = "EntityModule")
@Configuration
public class UserEntitiesConfiguration implements EntityConfigurer
{
	@Override
	public void configure( EntitiesConfigurationBuilder configuration ) {
		// By default permissions cannot be managed through the user interface
		configuration.entity( Permission.class ).hide();
	}
}
----

=== Creating an EntityConfiguration manually

=== Automatic registration of entity types

== Integration with other modules

[[integration:adminwebmodule]]
==== AdminWebModule

If the `AdminWebModule` is present entity management controllers will be created for all registered entity configurations.
If you want to avoid the automatic registration of entity management controllers for a particular entity type, you should
set the `EntityConfiguration` as `hidden`.  This will effectively disable the default entity controllers for that type,
and hide the existence of the entity type from the administration interface.

You can also hide one or more associations.  By default an association will not be shown if one of the participating
entities is hidden.  If you specify the `hidden` property of an `EntityAssociation` explicitly, that value will take
precendence of the entity configurations.  This way it is possible to generate management pages for associated
entities, but not for the main entity type.

== Entity associations

The `EntityModule` attempts to automatically detect related entities and creates associations mainly to facilitate UI
generation.  Currently `@OneToMany`, `@ManyToMany` and `@ManyToOne` annotations from `javax.persistence` API are all
scanned and used to build `EntityAssociation` entries.

In the administrative UI the management of related entities can often be done either through the property or the association.
This is especially the case for `@ManyToMany` and `@OneToMany` associations that are mapped through a property with collection type.
By default related entity management will be done through the property and the association will be generated but hidden.

NOTE: If you want to enable management through the association interface, you should manipulate the `hidden` property of
both the association and the property using an `EntityConfigurer`.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Override
public void configure( EntitiesConfigurationBuilder configuration ) {
    // Groups should be managed through the association instead of the property
    configuration.entity( MachinePrincipal.class )
                 .properties().property( "groups" ).hidden( true ).and().and()
                 .association( "machinePrincipal.groups" ).show();
}
----


== Entity views

=== List views

==== List summary view

It is possible to activate a detail view inline in a list view.  If the `EntityConfiguration` or `EntityAssociation` has
as view named *listSummaryView* a summary pane will automatically become available when clicking on the item row in the table.
The summary pane is called using AJAX and only the _content_ fragment of the page will be rendered.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
// Activate a summary view in the main user results table using a custom Thymeleaf template
configuration.entity( User.class ).view( EntityListView.SUMMARY_VIEW_NAME ).template( "th/myModule/userSummary" );
----

=== Custom views

=== EntityLinkBuilder

An `EntityConfiguration` or `EntityAssociation` can have one or more `EntityLinkBuilder` instances registered in its atttributes.
An `EntityLinkBuilder` is used to create application links to management controllers for the entity.  By default the `EntityModule`
will create an `EntityLinkBuilder` for the management pages in admin web if `AdminWebModule` is present, and this link builder
will be registered as the attribute with `EntityLinkBuilder` class as key.

You can use the `EntityLinkBuilder` directly for example in redirects, often the specific `EntityLinkBuilder` is overridable per view.
All links the `EntityLinkBuilder` generates are entirely configurable, please refer to the javadoc for all possible settings.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
EntityLinkBuilder linkBuilder = entityConfiguration.getAttribute( EntityLinkBuilder.class );

// Will create a link of the form "/entities/{parent}/{parentId}/update"
String path = linkBuilder.update( parent );
----

==== EntityLinkBuilder for associations
Associations usually also have an `EntityLinkBuilder` registered, it is possible to create links to items that are an association
from a parent entity.  To achieve this you must _scope_ the `EntityLinkBuilder` to the parent entity it belongs to.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
EntityLinkBuilder linkBuilder = entityConfiguration.getAttribute( EntityLinkBuilder.class );

EntityConfiguration associated = association.getTargetEntityConfiguration();
EntityLinkBuilder associatedLinkBuilder = association.getAttribute( EntityLinkBuilder.class )
                                                     .asAssociationFor( linkBuilder, parent );

// Will create a link of the form "/entities/{parent}/{parentId}/associations/{associationName}/{childId}/update"
String path = associatedLinkBuilder.update( child );
----


[[form-elements]]
== Form elements

Implementation is always disconnected from the selected value (entity).  Single form element could be used
to render multiple entities.

=== Form element types
Every `FormElement` has a unique element type `getElementType()`, this type is a simple String property that can be
 used how the element should render and behave.

.Common form element types
|===
|Element type |Description

|textbox
|

|hidden
|

|select
|

|multi-checkbox
|

|checkbox
|Renders a single checkbox.

|===

==== Type lookup strategy

.Default lookup strategy for common form element types
|===
|Property type |Form element type

| `String`, `Number`, `Date`
| textbox

| `Boolean`
| checkbox

| `Enum`
| select

| `Collection<?>`, `Array`
| multi-checkbox

|===

==== Specifying the default type for a property

=== Form element factories
hierarchy: assembler, builderfactory, builder, element (scopes)

messagecoderesolver

=== Common FormElement implementations
==== Basic functionality
label, value, required, print, customTemplate

==== HiddenFormElement
Renders a hidden HTML input type.

==== CheckboxFormElement
Renders a single checkbox, the `isChecked(Object)` method can be used to determine if the checkbox should be checked
for the given entity.

==== TextboxFormElement
Renders either a text input type or a textarea depending on the `multiLine` property.
Supports `maxLength` property to specify the maximum length of text the box should support.

==== SelectFormElement
This implementation is used for several element types and can be used to render any collection of selected values.
The `options` property determines the list of possible values in the form of `SelectOption` instances.  The associated
`SelectFormElementBuilder` takes a `SelectOptionGenerator` implementation that is used to generate the list of possible
options when building the element.

`SelectFormElement` provides a setter method for `elementType` because the base implementation can easily be used
for different types of controls.  The default template renders both `select` and `multi-checkbox` element types
from `SelectFormElement` instances.

configuration:
defining a custom view
registering custom properties






