#
# Copyright 2014 the original author or authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
spring:
  datasource:
    url: jdbc:h2:../local-data/db/entity-module
    username: sa
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 10MB

acrossModule:
  EntityModule:
    resources: ../entity-module/src/main/resources
  SpringDataJpaModule:
    resources: ../entity-shared-test/src/main/resources

adminWebModule:
  title: Entity Test Application
  login:
    rememberMe:
      key: test

debugWebModule:
  security:
    enabled: false
across:
  development:
    active: true

entityModule:
  message-codes:
    SpringDataJpaModule: spring-data

acrossHibernate:
  hibernate-properties:
    hibernate.format_sql: true
    hibernate.use_sql_comments: true
    hibernate.show_sql: true
    hibernate.hbm2ddl.auto: update

server:
  error:
    include-stacktrace: always
  port: 8081
