= ApplicationInfoModule
Arne Vandamme
1.0.1.RELEASE
:toc: left
:sectanchors:
:module-version: 1.0.1.RELEASE
:module-name: ApplicationInfoModule
:module-artifact: application-info-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/ApplicationInfoModule
:debug-web-module-url: https://foreach.atlassian.net/wiki/display/AX/DebugWebModule
:admin-web-module-url: https://foreach.atlassian.net/wiki/display/AX/AdminWebModule

[copyright,verbatim]
--
Copyright (C) 2014-2015 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

[abstract]
== About
The ApplicationInfo module configures an `AcrossApplicationInfo` bean that provides basic information of the running application.
It also provides a debug web controller to view the running application information.

Module website: {module-url}

:numbered:
== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

|===
|Module |Type |Description

|{debug-web-module-url}[DebugWebModule]
|extension
|Registers an application info overview as dashboard page for debug web.

|{admin-web-module-url}[AdminWebModule]
|extension
|Will use the configured application name and id as default settings for admin web.

|===
[[settings]]
=== Module settings

|===
|Property |Type |Description |Default

|applicationInfo.application-id
|`String`
| Internal id of the application.
|_unknown_

|applicationInfo.application-name
|`String`
| Descriptive name of the application.
|_null_

|applicationInfo.environment-id
|`String`
| Internal id of the environment the application is running in.
|_unknown_

|applicationInfo.environment-name
|`String`
| Descriptive name of the environment the application is running in.
|_null_

|applicationInfo.host-name
|`String`
| Name for the infrastructure hosting the application.
|Auto-detected.

|applicationInfo.build-id
|`String`
| Id of the running build of the application.
|_unknown_

|applicationInfo.build-date
|`Date`
| Timestamp when this build was created.
|_null_

|applicationInfo.startup-date
|`Date`
|Timestamp when the application should be considered started.
|Across context bootstrap time.

|===

NOTE: Timestamps in property files should be provided in *yyyy-MM-dd HH:mm:ss* format.

== What's new in this version?
:numbered!:
=== 1.0.1.RELEASE
This version introduces a couple of breaking changes:

* Package has been renamed from *com.foreach.across.module* to *com.foreach.across.modules*.
* If DebugWebModule present, DebugWebModule version should be at least 1.0.1
* If AdminWebModule present, AdminWebModule version should be at least 1.1.1

=== 1.0.0.RELEASE
Initial public release available on http://search.maven.org/[Maven central].

:numbered:
== Configuration
The purpose of the ApplicationInfoModule is to be able to uniquely identify a running application instance.
This is usually done through the combination of 3 parameters:

 * name of the application (eg. My Application)
 * name of the environment  (eg. Test)
 * name of the infrastructure hosting the application - usually a hostname (eg. my-server.lan)

Every parameter can be configured manually using the <<settings,module settings>>.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
ApplicationInfoModule applicationInfoModule = new ApplicationInfoModule();
applicationInfoModule.setProperty( ApplicationInfoModuleSettings.APPLICATION_ID, "demo-webapp");
applicationInfoModule.setProperty( ApplicationInfoModuleSettings.APPLICATION_NAME, "Across Demo Webapplication");
applicationInfoModule.setProperty( ApplicationInfoModuleSettings.ENVIRONMENT_ID, "demo");
applicationInfoModule.setProperty( ApplicationInfoModuleSettings.ENVIRONMENT_NAME, "Demo environment");

applicationInfoModule.setProperty( ApplicationInfoModuleSettings.BUILD_ID, "demo-webapp");
applicationInfoModule.setProperty( ApplicationInfoModuleSettings.BUILD_DATE, new Date());

context.addModule( applicationInfoModule );
----

== AcrossApplicationInfo
Once bootstrapped, the {module-name} exposes an `AcrossApplicationInfo` bean that contains the runtime settings.
This bean has a property *instanceId* that combines application, environment and hostname into a single `String` that uniquely identifies the application instance.

== Integration with other modules
=== DebugWebModule
{module-name} provides a debug web controller that displays the `AcrossApplicationInfo` settings.
This controller is available on the */applicationInfo* path relative to the debug web root.

If no explicit debug web dashboard has been configured, the {module-name} will also configure the application info controller as dashboard.

=== AdminWebModule
If AdminWebModule is present the {module-name} will automatically set the properties *adminWebModule.title* and *adminWebModule.login.rememberMe.cookie* based on the application info.
This will only happen if those properties have not yet been defined through some other means.


