= PropertiesModule
Arne Vandamme
1.1.1.RELEASE
:toc: left
:sectanchors:
:module-version: 1.1.1.RELEASE
:module-name: PropertiesModule
:module-artifact: properties-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/PropertiesModule
:application-info-url: https://foreach.atlassian.net/wiki/display/AX/PropertiesModule

[copyright,verbatim]
--
Copyright (C) 2014-2015 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

[abstract]
== About

The Properties module provides facilities to extend existing entities with custom properties, with optional revision tracking.

Module website: {module-url}

:numbered:
== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

{module-name} only has a optional dependencies on AcrossWebModule, EntityModule and AdminWebModule.

.Module dependencies
|===
|Module |Type |Description

|<<integration:adminweb-entity,EntityModule>>
|optional
|In combination with `AdminWebModule` this enables the management forms in the administration UI.
|===

=== Module settings

All properties start with the *propertiesModule.* prefix.

|===
|Property |Type |Description |Default

|conversionService
|`org.springframework.core.convert.ConversionService`
|Optional ConversionService instance to be used to convert properties. Defaults to the default ConversionService if none is specified.
|

|conversionServiceBean
|`java.lang.String`
|Optional The name of the ConversionService instance to be used to convert properties.
|
|===

== What's new in this version?
:numbered!:
=== 1.1.1.RELEASE

* Switched `PropertiesModuleSettings` to `@ConfigurationProperties` instead of the deprecated `AcrossModuleSettings`
* settings now support Spring configuration metadata

:numbered:
== Configuration

=== Installers
In order to extend existing entities with properties, the tables for these properties have to be installed.
The client application can do this by registering installers that extend from EntityPropertiesInstaller or RevisionBasedEntityPropertiesInstaller.

=== Repositories
The Properties module offers a base implementation of EntityPropertiesRepository that can be extended with a typed implementation.

=== Services
The client application should then extend either AbstractEntityPropertiesService or AbstractRevisionBasedEntityPropertiesService.
These services can then be wired into the entity services and used as described below.

=== Registries
The entities with properties should have a registry class extending from EntityPropertiesRegistry.
Registries are classes that contain a map for the properties added to a specific entity.
For example, a User entity class can have a corresponding UserPropertiesRegistry class.

=== Properties configuration
The properties for a specific entity are configured in a configuration class extending from AbstractEntityPropertiesConfiguration.
This class will specify the entity class, table name, the identifying column name and wire all classes extended as described above.

=== Property registration
The client application should register the properties during application startup as follows:
```java
@PostConstruct
protected void registerProperties() {
    userPropertiesRegistry.register( currentModule, "registration_code", String.class );
}
```
This snippet should be contained in a configuration class and autowire the current module and the specific EntityPropertiesRegistry for which this configuration is happening:
```java
@Autowired
@Module(AcrossModule.CURRENT_MODULE)
private AcrossModule currentModule;

@Autowired
private UserPropertiesRegistry userPropertiesRegistry;
```

This registry contains the definition of the property key to its implementation class and optionally a default value.
See EntityPropertiesRegistry for all available options.

==== Defaults
The Properties module supports simple types and parametrized types for registries. When registering a mapping, the client application can supply a default value.
These defaults should not be changed by client code. In order to enforce this, the Properties module uses PropertyFactory from the Foreach common libraries as a way to construct these defaults.
TypeDescriptors (from Spring) are used to describe the parameter types.

Examples:
```java
// A SingletonPropertyFactory used for an enum:
userPropertiesRegistry.register( currentModule, "enum_property", AnEnum.class,
                                 SingletonPropertyFactory.<String, AnEnum>forValue( AnEnum.SOME_VALUE ) );
// An anonymous implementation of PropertyFactory for a Set of Foo (which is an entity):
userPropertiesRegistry.register( currentModule,
                                 "userFoo",
                                 TypeDescriptor.collection( Set.class, TypeDescriptor.valueOf( Foo.class ) ),
                                 new PropertyFactory<String, Object>()
                                 {
                                     @Override
                                     public Object create( PropertyTypeRegistry registry, String propertyKey ) {
                                         return new HashSet<Foo>();
                                     }
                                 }
);
```

== Usage
If the Properties module is configured correctly and the services are wired, the properties of a specific entity can be read and set as follow:
```java
Foo foo = new Foo( "aFoo" );
UserProperties userProperties = userPropertiesService.getProperties( userId );
Set<Foo> foos = userProperties.getValue( "userFoo" );
foos.add( foo );
userPropertiesService.saveProperties( userProperties );
```
_Note that properties should always be saved after updating._